**Цель работы:**

Осуществить предварительную обработку данных csv-файла, выявить и устранить проблемы в этих данных.

# Загрузка набора данных

### Описание предметной области

Вариант №1

Набор данных: датасет drivers.csv содержит информацию о поездках такси.  
Атрибуты:
1. Дата и время начала
2. Дата и время окончания
3. Категория
4. Место начала
5. Место окончания
6. Пройденные мили
7. Цель поездки

### 1.Чтение файла (набора данных)

In [1]:
import pandas as pd # импорт библиотеки
df = pd.read_csv('drivers.csv') # чтение данных из файла

Исходные табличные данные преобразуются в датафрейм. 
DataFrame() – конструктор из библиотеки pandas. Датафрейм – двумерная структура данных в pandas, как и таблица, которая имеет две координаты: строка и столбец.

### 2. Обзор данных

#### 2.1 Вывод первых 20 строк с помощью метода head.

In [2]:
# примениение метода head, выводящего первые n строк (по умолчанию 5)
df.head(20)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*,time,speed,price
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,6.0,51.000000,788.0
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,NaN,12.0,25.000000,1237.0
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,13.0,22.153846,1312.0
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,14.0,20.142857,1387.0
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,67.0,57.044776,5376.0
5,2016-01-06 17:15:00,2016-01-06 17:19:00,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain,4.0,64.500000,638.0
6,2016-01-06 17:30:00,2016-01-06 17:35:00,Business,West Palm Beach,Palm Beach,7.1,Meeting,5.0,85.200000,714.0
7,2016-01-07 13:27:00,2016-01-07 13:33:00,Business,Cary,Cary,0.8,Meeting,6.0,8.000000,787.0
8,2016-01-10 08:05:00,2016-01-10 08:25:00,Business,Cary,Morrisville,8.3,Meeting,20.0,24.900000,1838.0
9,2016-01-10 12:17:00,2016-01-10 12:44:00,Business,Jamaica,New York,16.5,Customer Visit,27.0,36.666667,2365.0
10,2016-01-10 15:08:00,2016-01-10 15:51:00,Business,New York,Queens,10.8,Meeting,43.0,15.069767,3562.0
11,2016-01-10 18:18:00,2016-01-10 18:53:00,Business,Elmhurst,New York,7.5,Meeting,35.0,12.857143,2962.0
12,2016-01-10 19:12:00,2016-01-10 19:32:00,Business,Midtown,East Harlem,6.2,Meeting,20.0,18.600000,1837.0
13,2016-01-11 08:55:00,2016-01-11 09:21:00,Business,East Harlem,NoMad,6.4,Temporary Site,26.0,14.769231,2287.0
14,2016-01-11 11:56:00,2016-01-11 12:03:00,Business,Flatiron District,Midtown,1.6,Errand/Supplies,7.0,13.714286,862.0
15,2016-01-11 13:32:00,2016-01-11 13:46:00,Business,Midtown,Midtown East,1.7,Meal/Entertain,14.0,7.285714,1386.0
16,2016-01-11 14:30:00,2016-01-11 14:43:00,Business,Midtown East,Midtown,1.9,Meal/Entertain,13.0,8.769231,1312.0
17,2016-01-12 12:33:00,2016-01-12 12:49:00,Business,Midtown,Hudson Square,1.9,Meal/Entertain,16.0,7.125000,1536.0
18,2016-01-12 12:53:00,2016-01-12 13:09:00,Business,Hudson Square,Lower Manhattan,4.0,Meal/Entertain,16.0,15.000000,1537.0
19,2016-01-12 14:42:00,2016-01-12 14:56:00,Business,Lower Manhattan,Hudson Square,1.8,Errand/Supplies,14.0,7.714286,1386.0

При запуске фрагмента кода отображается начало исходной таблицы. Помимо перечисленных атрибутов каждая запись имеет уникальный id (первый столбец), а также поля время (разность времени окончания и времени начала поездки), скорость движения, цена поездки. 
    Также существуют методы tail() и sample(), которые возвращают 5 последних или случайных строк датасета соответственно.

#### 2.2 Оценка данных с помощью метода info.

Данные, которые хранятся в csv-файлах и используются для анализа, могут содержать ошибки, которые необходимо устранить перед непосредственным анализом. Метод info() предоставляет общую информацию о таблице: её размеры, названия столбцов, типы данных значений, хранящихся в них, а также количество ненулевых значений в каждом столбце.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1099 entries, 0 to 1098
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START_DATE*  1099 non-null   str
 1   END_DATE*    1099 non-null   str
 2   CATEGORY*    1099 non-null   str
 3   START*       1099 non-null   str
 4   STOP*        1099 non-null   str
 5   MILES*       1099 non-null   float64
 6   PURPOSE*     598 non-null    str
 7   time         1099 non-null   float64
 8   speed        1099 non-null   float64
 9   price        1099 non-null   float64
dtypes: float64(4), str(6)
memory usage: 162.9 KB

    Датасет состоит из 10 столбцов и содержит 1099 строк, при этом все атрибуты, кроме цели поездки, не содержат ни одного пропуска. Поле PURPOSE имеет лишь 598 ненулевых значений, т.е. у значительной части записей нет данных о цели поездки, *столбец требует отдельной обработки*.
    Названия столбцов START и STOP не отображают информацию, которая в них содержится, поэтому в дальнейшем для ясности стоит их переименовать.
    Также отображается информация о типах данных столбцов: START_DATE*, END_DATE*, CATEGORY*, START*, STOP* имеют строковый тип str, а остальные - вещественные числа float64. Даты, сохранённые в формате str, не удобно анализировать, поэтому требуется преобразовать их в тип datetime.

#### 2.3 Оценка данных с помощью метода describe.

In [4]:
# оценка числовых столбцов
df.describe()

C:\AppDataScience\anaconda3\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

            MILES*         time        speed         price
count  1099.000000  1099.000000  1099.000000   1099.000000
mean     10.803094    23.300273          inf   2085.929936
std      22.044580    27.745836          NaN   2084.368402
min       0.500000     0.000000     3.917355    337.000000
25%       2.900000    10.000000    15.346667   1087.000000
50%       6.000000    16.000000    21.333333   1539.000000
75%      10.500000    27.000000    28.915033   2365.500000
max     310.300000   336.000000          inf  25569.000000

С помощью метода describe оцениваются числовые столбцы: выводится среднее, минимальное и максимальное значения, стандартное отклонение и квартили. 
При запуске кода выводится предупреждение о недопустимом значении при вычитании, в результате чего некоторые числовые характеристики атрибута speed посчитаны некорректно: mean - inf (положительная бесконечность), std - NaN (пустое значение), max - inf. Это говорит о некорректных данных в поле скорости, *столбец требует отдельной обработки*.

#### 2.4 Оценка названий столбцов

**Предобработка** - подготовка данных для анализа, которая заключается в поиске проблем в данных, оценивании их масштаба и устранении этих проблем. 
***
Типичные проблемы в названиях столбцов:
- пробелы в названиях (лучше избегать использования пробелов и вместо
них использовать символ подчеркивания)
- в названиях используются разные языки
- непонятные названия столбцов, которые не отражают суть содержащихся в нём данных

In [5]:
# Вывод на экран названий столбцов с помощью df.columns.
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*', 'time', 'speed', 'price'],
      dtype='str')

Все названия приводятся к общему виду: латинские строчные буквы, без лишних символов.

In [6]:
df = df.rename(columns={'START_DATE*':'start_date', 'END_DATE*':'end_date', 'CATEGORY*':'category', 'START*':'start_loc', 'STOP*':'stop_loc', 'MILES*':'miles', 'PURPOSE*':'purpose'})

### 3. Проверка пропусков

В пункте 2.3 были выявлены нулевые значения в столбце time, которые исказили результаты начального статистического анализа числового столбца speed, поэтому в первую очередь стоит обработать эти строки.

In [7]:
import numpy as np
df.loc[df['time'] == 0, 'time'] = np.nan

In [8]:
# Проверка данных на наличие пропусков
df.isna().sum()

start_date      0
end_date        0
category        0
start_loc       0
stop_loc        0
miles           0
purpose       501
time            4
speed           0
price           0
dtype: int64

Оказывается, есть всего 4 строки с нулевым значением времени. Пропуски такого рода можно сразу удалить, поскольку в масштабе всего датасета потеря данных будет незначительна.

In [9]:
# Удаление строк, в которых в столбцах time есть None
df = df.dropna(subset=['time'])

Как было замечено ранее, столбец purpose содержит много пропусков. Будем считать, что в дальнейшем исследовании данный признак не играет важной роли, поэтому пропуски можно заполнить значением по умолчанию (если полностью удалить эти строки, будет потеряна значительная часть собранных данных). Однако замена пропущенного значения одним из представленных вариантов (Meal, Meeting, Customer Visit и т.д.) сильно исказит распределение целей поездок, поэтому используется новое значение "Unknown Purpose".

In [10]:
df['purpose'] = df['purpose'].fillna('Unknown Purpose')
df.isna().sum()

start_date    0
end_date      0
category      0
start_loc     0
stop_loc      0
miles         0
purpose       0
time          0
speed         0
price         0
dtype: int64

После удаления строк желательно обновить индексацию, чтобы избавиться от пропусков. Метод reset_index() создаст новый датафрейм, в котором: 
- индексы исходного датафрейма станут новой колонкой с названием index ;
- все строки получат обычные индексы, уже без пропусков.

In [11]:
df = df.reset_index(drop=True)

### 4. Проверка дубликатов

#### Проверка явных дубликатов

**Явными дубликатами** считаются те строки, которые полностью повторяют уже встречавшиеся в датасете. Для их поиска используется метод `duplicated()`. 
Логическая индексация - это способ фильтрации данных, при котором внутрь квадратных скобок передаётся не список имен столбцов, а последовательность значений True и False (булева маска). Она накладывается на датафрейм и возвращает только те строки, для которых в объекте series (результатом метода `duplicated()`) было True.

In [12]:
df[df.duplicated()] # получение дубликатов с помощью логической индексации
print(df.duplicated().sum()) # подсчет количества дубликатов

0

Полностью одинаковых строк в датасете не наблюдается.

#### Проверка неявных дубликатов

**Неявные дубликаты** - это альтернативные написания одного и того же значения, ошибочные написания слов. Их ищут с помощью unique() , который возвращает перечень уникальных значений в столбце.

In [13]:
df.columns

Index(['start_date', 'end_date', 'category', 'start_loc', 'stop_loc', 'miles',
       'purpose', 'time', 'speed', 'price'],
      dtype='str')

In [14]:
print(df['category'].unique())
df['category'].value_counts() # вывод уникальных значений и их частоты

<ArrowStringArray>
['Business', 'Personal']
Length: 2, dtype: str

category
Business    1018
Personal      77
Name: count, dtype: int64

In [15]:
print(df['purpose'].unique())
df['purpose'].value_counts()

<ArrowStringArray>
[ 'Meal/Entertain', 'Unknown Purpose', 'Errand/Supplies',         'Meeting',
  'Customer Visit',  'Temporary Site', 'Between Offices',     'Charity ($)',
         'Commute',          'Moving',  'Airport/Travel']
Length: 11, dtype: str

purpose
Unknown Purpose    497
Meeting            178
Meal/Entertain     145
Errand/Supplies    110
Customer Visit      94
Temporary Site      46
Between Offices     17
Moving               4
Airport/Travel       2
Charity ($)          1
Commute              1
Name: count, dtype: int64

Данные столбцов category и purpose стандартизированы. Дубликатов, вызванных ошибками в записи, разным регистром или языком, не обнаружено.

### 5. Провека типов данных

Чтобы избавиться от неявных дубликатов в столбцах с датами (например, "01.01.2023", "2023-01-01", "Jan 1, 2023"), стоит привести значения к общему формату datetime (сейчас str).

In [16]:
df['start_date'] = pd.to_datetime(df['start_date'], format = '%Y-%m-%d %H:%M:%S', errors='coerce')
df['end_date'] = pd.to_datetime(df['end_date'], format = '%Y-%m-%d %H:%M:%S', errors='coerce')
print(df['start_date'].dtype)
print(df['end_date'].dtype)

datetime64[us]
datetime64[us]

Аргумент errors='coerce' осуществляет принудительную замену значений, которые pandas не смог привести к типу datetime, на NaN (пропуск). Выясним, сколько строк "сломалось" после преобразования:

In [17]:
df.isna().sum()

start_date    0
end_date      0
category      0
start_loc     0
stop_loc      0
miles         0
purpose       0
time          0
speed         0
price         0
dtype: int64

Датасет не содержит пустых ячеек, то есть изначально каждая строка содержала корректную запись даты начала и окончания поездки.

In [18]:
print(df.duplicated().sum())

0

Датасет не содержит дубликатов ни по одному из признаков.

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   start_date  1095 non-null   datetime64[us]
 1   end_date    1095 non-null   datetime64[us]
 2   category    1095 non-null   str
 3   start_loc   1095 non-null   str
 4   stop_loc    1095 non-null   str
 5   miles       1095 non-null   float64
 6   purpose     1095 non-null   str
 7   time        1095 non-null   float64
 8   speed       1095 non-null   float64
 9   price       1095 non-null   float64
dtypes: datetime64[us](2), float64(4), str(4)
memory usage: 129.2 KB

### 6. Группировка данных

Группировка данных позволяет осуществить более подробное изучение материала, чтобы затем искать связи между отдельными группами. Процесс группировки может быть выражен формулой "разделить-применитьобъединить" (split-apply-combine). Данные разбиваются на группы в соответствии с определенным признаком, затем к каждой группе применяются различные вычислительные методы, такие как подсчет количества элементов в группе с помощью метода `count()` или суммирование элементов с помощью метода `sum()` . После этого результаты объединяются в новую таблицу.
Группировка в pandas осуществляется с помощью `groupby()`:
- метод принимает в качестве аргумента название столбца, по которому нужно группировать (например, год, пол, категория).
- метод возвращает объект типа DataFrameGroupBy , то есть сгруппированные
данные, к которым можно применять различные методы (count, sum, min, max,
mean, last). Если применить к ним какой-нибудь метод pandas, они станут
новой структурой данных типа DataFrame или Series .

#### Задание 1

*`Группировка - CATEGORY и количество поездок каждого типа
(по цели маршрута).`*

df.groupby('category') — это промежуточный объект типа DataFrameGroupBy, который хранит инструкцию о том, как разделить данные на группы. Он не выполняет никаких вычислений, пока к нему не применить соответствующий метод.

In [20]:
# df.groupby(['category', 'purpose'])['price'].count()
df.groupby(['category', 'purpose']).size() # рез. не зависит от наличия пропусков

category  purpose
Business  Airport/Travel       2
          Between Offices     17
          Customer Visit      94
          Errand/Supplies    110
          Meal/Entertain     145
          Meeting            178
          Temporary Site      46
          Unknown Purpose    426
Personal  Charity ($)          1
          Commute              1
          Moving               4
          Unknown Purpose     71
dtype: int64

Личных поездок оказалось значительно меньше, чем бизнес-поездок (77 против 1018), причем чаще всего цель личной поездки не указывалась (Unknown Purpose - 71 из 77). Среди бинес-поездок также преобладают записи без указанной цели (426 из 1018), что составляет около 45% от всех данных. Из указанных чаще всего встречаются поездки на деловые встречи (Meeting), на деловые обеды/развлечения (Meal/Entertain), а также поездки за покупками/по поручению (Errand/Supplies).

#### Задание 2

*`Группировка - CATEGORY и количество поездок для каждой
точки старта (START). Создать датафрейм. Переименовать столбец с
количеством в “сount”. Отсортировать по возрастанию столбца “count”.`*

In [21]:
grouped2 = df.groupby(['category', 'start_loc']).size() # создание объекта Series
grouped2 = grouped2.reset_index(name='count').sort_values(by = 'count')
print(grouped2)

     category                  start_loc  count
1    Business                     Almond      1
3    Business                      Arabi      1
5    Business  Arlington Park at Amberly      1
4    Business                  Arlington      1
7    Business                     Austin      1
..        ...                        ...    ...
63   Business                  Islamabad     51
164  Business                Whitebridge     59
95   Business                Morrisville     79
151  Business           Unknown Location    133
16   Business                       Cary    198

[199 rows x 3 columns]

Для более четкой интерпретации дополнительно проводится расчёт ключевых характеристик набора данных count.

In [22]:
grouped2.describe()

            count
count  199.000000
mean     5.502513
std     18.595338
min      1.000000
25%      1.000000
50%      1.000000
75%      3.000000
max    198.000000

Распределение количеств поездок имеет правостороннюю симметрию: медиана равна 1, то есть для большинства точек старта (более 50%) зафиксирована только одна поездка. При этом среднее значение составляет 5.5, а максимум достигает 198, что указывает на наличие нескольких популярных локаций. **Самыми популярными являются бизнес-поездки из Cary (198), Morrisville (79) и Whitebridge (59)**, а для многих бизнес-поездок точка старта не указана (Unknown Location 133).
75% всех точек старта имеют не более 3 поездок, что подтверждает гипотезу о том, что подавляющее большинство локаций — это разовые адреса, а не регулярные маршруты.

#### Задание 3

*` Сводная таблица (pivot_table) - среднее количество пройденных миль по каждой цели поездки (PURPOSEroute). Отсортировать по убыванию столбца MILES. Округлить значение до двух
знаков.
`*

In [23]:
pivot_df = df.pivot_table(index='purpose', values='miles', aggfunc='mean')
pivot_df = pivot_df.sort_values(by = 'miles', ascending = False).round(2)
print(pivot_df)

                  miles
purpose
Commute          180.20
Customer Visit    21.90
Meeting           15.59
Charity ($)       15.10
Between Offices   11.23
Temporary Site    10.01
Unknown Purpose    9.68
Airport/Travel     6.20
Meal/Entertain     5.66
Moving             4.55
Errand/Supplies    4.14

Из полученной сводной таблицы видно, что наибольшая средняя дальность поездки зафиксирована для категории Commute (180.2 мили). Данное значение вызывает сомнения, так как Commute (поездка на работу) обычно подразумевает короткие расстояния. Причиной такого высокого среднего может быть единичный выброс в данных, ведь данная сводная таблица не учитывает частоту поездок (количество записей в каждой категории), что может привести к ошибочным выводам: категории с единичными записями могут искажать картину. Для корректной интерпретации данных необходимо дополнительно рассчитать количество поездок для каждой цели.

In [24]:
pivot_df = df.pivot_table(
    index='purpose', 
    values='miles', 
    aggfunc=['mean', 'count']# выводится и среднее, и количество
).round(2).sort_values(by = ('mean', 'miles'), ascending = False)

print(pivot_df)

                   mean count
                  miles miles
purpose
Commute          180.20     1
Customer Visit    21.90    94
Meeting           15.59   178
Charity ($)       15.10     1
Between Offices   11.23    17
Temporary Site    10.01    46
Unknown Purpose    9.68   497
Airport/Travel     6.20     2
Meal/Entertain     5.66   145
Moving             4.55     4
Errand/Supplies    4.14   110

Лидирующее значение 180.20 миль для Commute было рассчитано на основе единичной поездки, что может указывать на ошибку или выброс данных. Среди более массовых лидируют поездки с целью визита клиента (средняя дальность 21.9 миль) и поездки на деловые встречи (15.59 миль), что выглядит реалистично.

#### Задание 4

*`Сводная таблица (pivot_table) - среднее количество
пройденных миль по каждой цели каждой категории(CATEGORY*) -
столбцы и каждой точке старта START - строки. Отсортировать по
убыванию столбца START. Округлить значения с помощью round.
`*

In [25]:
pivot_df1 = df.pivot_table(
    index='start_loc',
    columns=['category','purpose'],
    values='miles', 
    aggfunc='mean')
pivot_df1 = pivot_df1.sort_index(ascending = False).round(2)
display(pivot_df1)

category              Business                                                 \
purpose         Airport/Travel Between Offices Customer Visit Errand/Supplies
start_loc
Winston Salem              NaN             NaN            NaN             NaN
Whitebridge                NaN             6.1           7.10            2.76
Westpark Place             NaN             NaN            NaN            2.00
Weston                     NaN             NaN            NaN             NaN
West University            NaN             NaN            NaN             NaN
...                        ...             ...            ...             ...
Arlington                  NaN             NaN            NaN             NaN
Arabi                      NaN             NaN            NaN             NaN
Apex                       NaN             NaN           5.36             NaN
Almond                     NaN             NaN            NaN             NaN
Agnew                      NaN             NaN            NaN             NaN

category                                                               \
purpose         Meal/Entertain Meeting Temporary Site Unknown Purpose
start_loc
Winston Salem              NaN  133.60            NaN             NaN
Whitebridge               5.58    6.33            NaN            3.07
Westpark Place            3.05     NaN            NaN            1.91
Weston                    3.80     NaN            NaN             NaN
West University           2.10     NaN            NaN            2.30
...                        ...     ...            ...             ...
Arlington                  NaN     NaN            NaN            4.90
Arabi                    17.00     NaN            NaN             NaN
Apex                      6.07    7.30            8.8            3.73
Almond                     NaN     NaN            NaN           15.20
Agnew                      NaN     NaN            NaN            2.78

category           Personal
purpose         Charity ($) Commute Moving Unknown Purpose
start_loc
Winston Salem           NaN     NaN    NaN             NaN
Whitebridge             NaN     NaN    NaN            2.33
Westpark Place          NaN     NaN    NaN            2.95
Weston                  NaN     NaN    NaN            4.20
West University         NaN     NaN    NaN             NaN
...                     ...     ...    ...             ...
Arlington               NaN     NaN    NaN             NaN
Arabi                   NaN     NaN    NaN             NaN
Apex                    NaN     NaN    NaN             NaN
Almond                  NaN     NaN    NaN             NaN
Agnew                   NaN     NaN    NaN             NaN

[174 rows x 12 columns]

Сводная таблица демонстрирует среднюю дальность поездок по каждой комбинации "точка старта — категория — цель". Из-за высокой детализации (174 точки старта x 12 категорий) таблица содержит большое количество пропусков (NaN), что означает отсутствие поездок данного типа из конкретной локации.

### Вывод

В ходе работы был проанализирован датасет drivers.csv, содержащий информацию о поездках такси. Предобработка данных включала несколько этапов: приведение названий столбцов к единому виду, проверку на явные и неявные дубликаты (дубликатов не выявлено), обработку пропусков и корректировку типов данных. В частности, были удалены 4 строки со значением time=0, пропуски в поле purpose (501 запись) заменены на категорию Unknown Purpose, а столбцы start_date и end_date приведены к формату datetime. Итоговый размер очищенного датасета составил 1095 строк и 10 столбцов.

Анализ группировок показал, что бизнес-поездки (1018) количественно преобладают над личными (77). При этом почти половина всех записей (497) не содержит информации о цели поездки. Среди указанных целей чаще всего встречаются деловые встречи (Meeting — 178), обеды/развлечения (Meal/Entertain — 145) и поездки за покупками/поручениями (Errand/Supplies — 110).

Группировка по точкам старта (start_loc) выявила, что наиболее популярными являются бизнес-поездки из Cary (198), Morrisville (79) и Whitebridge (59). Для 133 бизнес-поездок точка старта не указана (Unknown Location). При этом 75% всех точек старта имеют не более 3 поездок, что говорит о преобладании разовых адресов над регулярными маршрутами.

Сводные таблицы позволили оценить среднюю дальность поездок в разрезе целей и категорий. Наибольшее среднее значение (180.2 миль) зафиксировано для цели Commute, однако оно основано на единичной поездке и, вероятно, является выбросом. Среди массовых категорий лидируют визиты к клиентам (Customer Visit — 21.9 миль) и деловые встречи (Meeting — 15.59 миль). Детализированная сводная таблица по комбинации «точка старта — категория — цель» содержит большое количество пропусков (NaN), что отражает неравномерность распределения поездок и малый размер выборки для многих локаций.

### Дополнительное задание

Номера заданий: 1, 7, 9, 13.

**`Задание 1. Добавить столбец - время поездки (расчетный). Выполнить
группировку - среднее и медианное время поездки по категориям.`**

При вычитании дат автоматически образуется объект Timedelta - специальный тип данных в pandas, который представляет собой длительность. Он хранится внутри как количество наносекунд. Аксессор .dt — это специальный интерфейс, который «разбирает» этот формат на составные части (часы, минуты и т.д.).

In [42]:
df['drive_time'] = (df['end_date']-df['start_date']).dt.total_seconds()//60
df.head()

,start_date,end_date,category,start_loc,stop_loc,miles,purpose,time,speed,price,drive_time
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,6.0,51.000000,788.0,6.0
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,Unknown Purpose,12.0,25.000000,1237.0,12.0
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,13.0,22.153846,1312.0,13.0
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,14.0,20.142857,1387.0,14.0
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,67.0,57.044776,5376.0,67.0

In [43]:
df.groupby('category').agg({'drive_time': ['mean', 'median']})

         drive_time
               mean median
category
Business  23.607073   17.0
Personal  20.454545   15.0

Поездки категории Business в среднем длиннее (23.6 мин), чем Personal (20.5 мин). Если сранивать значения медианы и среднего, можно заметить, что для обеих категорий median > mean примерно на 6 минут (разница составляет около 25% величины - значительно для анализа). Распределение времени поездок отлично от нормального и имеет тяжелый правый хвост (правостороннюю асимметрию). Большинство поездок — короткие (около 15-17 минут), но есть некоторое количество очень долгих поездок (выбросов), которые искажают среднее значение, завышая его.

**`Задание 7. Добавить столбец - время поездки (расчетный). Создать столбец
“Категория длительности поездки” (с помощью категоризации).
Выделить минимум 3 категории (короткая, длинная, средняя),
фильтрацию для времени выбрать самостоятельно, аргументировать
выбор. Создать сводную таблицу: среднее количество пройденных
миль по категории длительности поездки и категории поездки.`**

**Категоризация** – объединение данных в категории, которая позволяет
классифицировать или группировать данные по определенным
признакам или критериям для более удобного и понятного их анализа. Для выбора границ фильтрации оценим числовые характеристики распределения:

In [85]:
df['drive_time'].describe()

count    1095.000000
mean       23.385388
std        27.760654
min         1.000000
25%        10.000000
50%        16.000000
75%        27.500000
max       336.000000
Name: drive_time, dtype: float64

Разделим значения длительности поездки на категории следующим образом:
- Короткие поездки:  drive_time <= 10 (меньше Q1);
- Средние поездки:  10< drive_time < 27.5 (между Q1 и Q3);
- Длинные поездки:  drive_time >= 27.5 (больше Q3);

Использование квартилей позволяет создать устойчивые к выбросам категории, отражающие реальную структуру данных: большинство поездок попадут в средний диапазон.

In [48]:
duration_cat = ['short', 'average', 'long']

df['duration_category'] = pd.cut(df['drive_time'], bins=[0, 10, 27.5, 350], labels=duration_cat) # длина списка меток на 1 меньше кол-ва интервалов
df.head()

,start_date,end_date,category,start_loc,stop_loc,miles,purpose,time,speed,price,drive_time,duration_category
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,6.0,51.000000,788.0,6.0,short
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,Unknown Purpose,12.0,25.000000,1237.0,12.0,average
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,13.0,22.153846,1312.0,13.0,average
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,14.0,20.142857,1387.0,14.0,average
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,67.0,57.044776,5376.0,67.0,long

In [80]:
df.groupby('duration_category')['speed'].count
# df['duration_category'].value_counts()

Получено балансированное распределение. Категория *average* закономерно самая большая, т.к. она охватывает межквартильный размах (50% всех данных).

 Переходим к созданию сводной таблицы: среднее количество пройденных миль по категории длительности поездки и категории поездки.

In [54]:
category_pivot = df.pivot_table(index='category', columns='duration_category', values='miles', aggfunc='mean')
display(category_pivot)

duration_category    short   average       long
category
Business           3.01637  7.192469  26.232819
Personal           1.86800  5.597297  30.926667

В таблице отсутствуют пропуски, что означает наличие данных для всех комбинаций категорий поездок и их длительности.
Прослеживается прямая зависимость: чем больше время в пути, тем больше средняя дальность поездки (в милях). Короткие и средние бизнес-поездки оказались в среднем дальше, чем персональные. Однако долгие по продолжительности личные поездки в среднем оказались поездками на большие расстояния, чем бизнес-поездки той же категории. Возможное объяснение: личные долгие поездки — это поездки за город или в другой город, а долгие бизнес-поездки могут быть долгим стоянием в пробках.

**`Задание 9. Добавить столбец - время поездки (расчетный). Создать столбец
“Категория длительности поездки” (с помощью категоризации).
Выделить минимум 3 категории (короткая, длинная, средняя),
фильтрацию для времени выбрать самостоятельно, аргументировать
выбор. Создать группировку: средняя и медианная длительность по
категории длительности поездки.`**

Большая часть требований уже выполнена в предыдущем задании. Сразу переходим к созданию группировки:

In [61]:
df.groupby('duration_category').agg({'drive_time': ['mean', 'median']})

                  drive_time
                        mean median
duration_category
short               6.970588    7.0
average            17.365049   17.0
long               53.032847   38.5

**`Задание 13. Добавить столбец - время поездки (расчетный). Создать столбец
“Категория пройденных миль” (с помощью категоризации). Выделить
минимум 3 категории (короткая, длинная, средняя), фильтрацию для
расстояния выбрать самостоятельно, аргументировать выбор.
Создать группировку: минимальная и максимальная длительность
поездки по категории пройденных миль.
`**

In [62]:
df['miles'].describe()

count    1095.000000
mean       10.774064
std        22.009426
min         0.500000
25%         2.900000
50%         6.000000
75%        10.500000
max       310.300000
Name: miles, dtype: float64

Воспользуемся методом qcut(), который автоматически делит набор данных на равновеликие группы. Границы категоризации проходят по квантилям.
    Это значит, что в каждый интервал попадает примерно одинаковое количество наблюдений, что полезно, когда данные распределены неравномерно или содержат выбросы.

In [83]:
df['miles_category'], bins = pd.qcut(x=df['miles'], q=3, labels=['short', 'average', 'long'], retbins=True)
df.head()

,start_date,end_date,category,start_loc,stop_loc,miles,purpose,time,speed,price,drive_time,duration_category,miles_category
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,6.0,51.000000,788.0,6.0,short,average
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,Unknown Purpose,12.0,25.000000,1237.0,12.0,average,average
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,13.0,22.153846,1312.0,13.0,average,average
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,14.0,20.142857,1387.0,14.0,average,average
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,67.0,57.044776,5376.0,67.0,long,long

In [84]:
print(df['miles_category'].value_counts())
print(bins)

miles_category
short      368
long       364
average    363
Name: count, dtype: int64
[  0.5   3.6   9.  310.3]

Распределение сбалансированно, каждая категория содержит примерно одинаковое кол-во поездок. Однако стоит учитывать, что из-за сильных выбросов (поездки на 300+ миль) категория long будет иметь очень широкий диапазон значений (например, от 9 до 310 миль).